### PR TITLE
Allow returning null for loadMoreItems

### PR DESCRIPTION
**Pull request by nicholas-l**
On L144 it allows returning null from function

### CODE REVIEW

**Comment by bvaughn** [comment]
Hm. I don't think a `null` return value is really _meant_ to be supported. That code is just to prevent a runtime error. `loadMoreItems` should always return a Promise.

**Comment by nicholas-l** [comment]
Awesome! I thought it allowed it since the example has:

```
  // Only load 1 page of items at a time.
  // Pass an empty callback to InfiniteLoader in case it asks us to load more than once.
  const loadMoreItems = isNextPageLoading ? () => {} : loadNextPage;
```

Should I update the readme?

**Comment by bvaughn** [comment]
Ah. Good point. Hm.

To be honest, it's been a long time since I wrote (or even used) this library 😄  The standalone package was just forked from react-virtualized

**Comment by nicholas-l** [comment]
Ah so we could just change the flow types? Not a huge change? 😄

**Comment by nareshbhatia** [comment]
I think this needs more analysis. There are two issues:

- I don't think the original code is working as intended - `loadMoreTimes` is not preventing recursion. It is actually allowing multiple pages to be loaded at the same time. If the calls happen to return in the correct order, then the items array is in the right state, otherwise it is messed up.
- If I convert the code to TypeScript, I get a TypeScript error, because `() => {}` is returning `void`, whereas the type definitions require a return of `Promise<any> | null`

To prove point 1, just add a console.log() when the page has finished loading.

```
  _loadNextPage = (...args) => {
    console.log("loadNextPage", ...args);
    this.setState({ isNextPageLoading: true }, () => {
      setTimeout(() => {
        this.setState(state => ({
          hasNextPage: state.items.length < 100,
          isNextPageLoading: false,
          items: [...state.items].concat(
            new Array(10).fill(true).map(() => ({ name: name.findName() }))
          )
        }));
        console.log("next page loaded", ...args);   // <---- ADD THIS
      }, 2500);
    });
  };
```

You will now see that the pages are loaded recursively:

```
loadNextPage 0 0
loadNextPage 10 10
next page loaded 0 0
next page loaded 10 10
```

I was not able to fix this behavior even after changing `loadMoreItems` to return Promise.resolve().

```
const loadMoreItems = isNextPageLoading
    ? () => { console.log("Just resolving promise"); return Promise.resolve() }
    : loadNextPage;
```

It seems that `isNextPageLoading` is never true and `loadNextPage` is called recursively anyway.

In my app, I was able to manage `isNextPageLoading` to become true at the right times. This indeed prevents recursion, but now the scroller thinks that the `loadMoreItems()` call is resolved and never calls it again!

I think a better solution would be for the scroller to keep some state to prevent recursive calls and call `loadMoreItems()` only when needed.

**Comment by eyea** [comment]
> I think this needs more analysis. There are two issues:
> 
> * I don't think the original code is working as intended - `loadMoreTimes` is not preventing recursion. It is actually allowing multiple pages to be loaded at the same time. If the calls happen to return in the correct order, then the items array is in the right state, otherwise it is messed up.
> * If I convert the code to TypeScript, I get a TypeScript error, because `() => {}` is returning `void`, whereas the type definitions require a return of `Promise<any> | null`
> 
> To prove point 1, just add a console.log() when the page has finished loading.
> 
> ```
>   _loadNextPage = (...args) => {
>     console.log("loadNextPage", ...args);
>     this.setState({ isNextPageLoading: true }, () => {
>       setTimeout(() => {
>         this.setState(state => ({
>           hasNextPage: state.items.length < 100,
>           isNextPageLoading: false,
>           items: [...state.items].concat(
>             new Array(10).fill(true).map(() => ({ name: name.findName() }))
>           )
>         }));
>         console.log("next page loaded", ...args);   // <---- ADD THIS
>       }, 2500);
>     });
>   };
> ```
> 
> You will now see that the pages are loaded recursively:
> 
> ```
> loadNextPage 0 0
> loadNextPage 10 10
> next page loaded 0 0
> next page loaded 10 10
> ```
> 
> I was not able to fix this behavior even after changing `loadMoreItems` to return Promise.resolve().
> 
> ```
> const loadMoreItems = isNextPageLoading
>     ? () => { console.log("Just resolving promise"); return Promise.resolve() }
>     : loadNextPage;
> ```
> 
> It seems that `isNextPageLoading` is never true and `loadNextPage` is called recursively anyway.
> 
> In my app, I was able to manage `isNextPageLoading` to become true at the right times. This indeed prevents recursion, but now the scroller thinks that the `loadMoreItems()` call is resolved and never calls it again!
> 
> I think a better solution would be for the scroller to keep some state to prevent recursive calls and call `loadMoreItems()` only when needed.

the same condition :(

**Pull request closed without merging**
